### ISSUE TITLE
elmahio.js:1698 Uncaught TypeError: Cannot read property 'captureConsoleMinimumLevel' of undefined

### ISSUE THREAD

**Issue by hollystyles** [elmahio/elmah.io.javascript#24]
Following steps [here](https://docs.elmah.io/logging-to-elmah-io-from-javascript)

1. Install elmah.io.javascript Nuget package to new ASP.Net MVC web application
2. Add `<script>` tag into _Layout page before other scripts immediately above closing `</body>` tag
3. F5 launch ASP.Net application
4. Default browser Microsoft Edge Version 85.0.564.44 (Official build) (64-bit)
5. F12 developer tools, console tab, observe error, I think caused by options being undefined. (see IssueScreenshot.png in attached zip archive)

Attached [ElmahJavascriptIssue.zip](https://github.com/elmahio/elmah.io.javascript/files/5167621/ElmahJavascriptIssue.zip)

**Comment by ThomasArdal** [comment]
Thank you very much for reporting this, Holly. We will look into it asap 👍

**Comment by ThomasArdal** [comment]
While we implement a fix for this, you can try creating the elmah.io.javascript logger like this:

```html
<script src="~/scripts/elmahio.min.js" type="text/javascript"></script>
```

```javascript
new Elmahio({
    apiKey: 'API_KEY',
    logId: 'LOG_ID'
});
```

**Comment by hollystyles** [comment]
Thank you for the quick response. I can confirm the work around works for me 👍

**Comment by ThomasArdal** [comment]
Happy to hear that. We have fixed the bug and plan to release a bugfix release later today. Sorry for the inconvenience.

**Comment by ThomasArdal** [comment]
A new NuGet package has been published. npm and documentation will follow. Thanks again.
