### ISSUE TITLE
Naming possible issue

### ISSUE THREAD

**Issue by Sojaner** [elmahio/elmah.io.javascript#6]
@ThomasArdal take a look at this issue:

[https://github.com/feimosi/baguetteBox.js/issues/200](https://github.com/feimosi/baguetteBox.js/issues/200)

They have `.js` in their library name which is making problems for people.

**Comment by ThomasArdal** [comment]
That's a good argument for renaming the package to `elmah.io.javascript`, actually. I think we'll do that in the next version. Thanks!
